// Test definitions. Do NOT edit this file!
#define CATCH_CONFIG_MAIN // defines main() automatically
#include "catch.hpp"
#include "main.hpp"
// tests for exercise 1
TEST_CASE("Ex1 ", "[Test 1]")
{
	int n1, n2, n3;
	float f1, f2;
	int ret1;
	float ret2;

	n1 = 20;
	n2 = 10;
	n3 = 15;

	cout << "The three values are " << n1 << "\t" << n2 << "\t" << n3 << endl;

	ret1 = myCompare(n1);
	cout << " Call myCompare(n1) " << ret1 << endl;
	REQUIRE(ret1 == 1);
	ret1 = myCompare(n1, n2);
	REQUIRE(ret1 == n1);
	cout << " Call myCompare(n1, n2) " << ret1 << endl;
	ret1 = myCompare(n1, n2, n3);
	REQUIRE(ret1 == n3);
	cout << " Call myCompare(n1, n2, n3) " << ret1 << endl;
	f1 = 19.3456;
	f2 = 21.9876;
	ret2 = myCompare(f1, f2);
	cout << " Call float myCompare(n1, n2) " << ret2 << endl;
	REQUIRE(ret2 > 2.6);
	REQUIRE(ret2 < 2.7);
}
// tests for exercise 2
TEST_CASE("Ex2 ", "[Test 2]")
{
	int n1, n2, n3;
	float f1, f2;
	int ret1;
	float ret2;

	n1 = -10;
	n2 = 15;
	n3 = 20;

	cout << "The three values are " << n1 << "\t" << n2 << "\t" << n3 << endl;

	ret1 = myCompare(n1);
	cout << " Call myCompare(n1) " << ret1 << endl;
	REQUIRE(ret1 == 0);
	ret1 = myCompare(n1, n2);
	REQUIRE(ret1 == n2);
	cout << " Call myCompare(n1, n2) " << ret1 << endl;
	ret1 = myCompare(n1, n2, n3);
	REQUIRE(ret1 == n2);
	cout << " Call myCompare(n1, n2, n3) " << ret1 << endl;
	f2 = 19.3456;
	f1 = 21.9876;
	ret2 = myCompare(f1, f2);
	cout << " Call float myCompare(n1, n2) " << ret2 << endl;
	REQUIRE(ret2 > 2.6);
	REQUIRE(ret2 < 2.7);
}