// Test definitions. Do NOT edit this file!
#define CATCH_CONFIG_MAIN // defines main() automatically
#include "catch.hpp"
#include "main.hpp"
// tests for exercise 1
TEST_CASE("Ex1", "[example]")
{
	int result = 0;
	int tmp = getRdnum();
	if ((tmp >= 0) && (tmp <= 10)
	    result  = 1;
	REQUIRE(result == 1 );
}
// tests for exercise 2
TEST_CASE("Ex2", "[example]")
{
	int result = 0;
	int tmp = getRdnum(20, 25);
	if ((tmp >= 20) && (tmp <= 25)
	    result  = 1;
	REQUIRE(result == 1);
}
// tests for exercise 3
TEST_CASE("Ex2", "[example]")
{
	int result = 0;
	int tmp = getRdnum(5);
	if ((tmp >= 0) && (tmp <= 5)
	    result  = 1;
	ON_FAILURE("The random value is not in the range");
	REQUIRE(result == 1);
}
